language: node_js

node_js:
  - 'node'
  - 'lts/*'

services:
  - xvfb

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
  - npm run build

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
