language: node_js
node_js:
- node
- lts/*
services:
- xvfb
env:
  global:
  - secure: DbgIoQKGEzCcjPpAc2R8KyVchz2qZQkJDo+zpoMaDY9LW1+y/yS0vYsv1cHTZRAyUJS8KJW57ptTSPKwr+cEPNJZ3lUDIrFjAtxmxFVtmo6VXYalS8xTeRIs3cZt/nJXAyJosgE4jDhf9LR3kfA2p1g62SCoY0LMuVuO/mCzfTm0KBT0XOtqbto6dzYzx1JmW8AqY4dl5uxee4/CDnR27K5HRqnQpedMJoBZ3rOKiY5jvIcgnA89CvpidWbD/bOxbXMAobXeh8LaKqv+Ip0gpfx/ZG35XGN6tsrsbf2klXEudh3xbs0WahWcPFu719awrzOdv1O4doJTQ3bpjedbD49o9KzBXQPR+S4u/6WlkHC04Smlb+Ra1LqBlE4UhK3d9i/1pXo5zXgjFDNoHjnPVNm+LmWPYpHs6zuAuecLueTzIHVIdHvP1mp5xpPGDVuukG/k8NiIm4FTvpsKnlazW6L+fVf6BulJEABZT/sua+3UFVGDMeQ/in1qiBNcDys9gKl8EJhY6l4gSK6yK3005KGvEotB2ILHan0VIEAcFdakZ2Zc/xHtnmchHks9BhA0WQof2OnR/MZ/cBdgNao2RekqjQuGiOztpfe3jJDJ3mcIIqVwkX/1EywTItfQIsP3An2b+Ci7Z45p6wkbp3n0nVSpVRPTUktGu7002aAz6VA=
  - secure: En/VtogSuGNFUDhkPoGHfG6yILXXShvuptnNxKFnd3KcHHyDBw/0Q6T+3T6XUyT78jzmBQXxgbvxguSfVTdPoiW4PmOcOVgU2iz5q8T2snjyFC2Bc8waBb7NZUVj4JsXmqfY0Y/LYGnqUsGxtttVGqeMP0Hvac4hRC8fjJzxt3aZKg/kIRkBHUor5KaAp+VkcCaWNKTHicLMFXWMYwjXFXxzgCpFWH7S19jqfU9UqsoZpHt4bmb52WaN1yN7uK9iTHv8rblDjksmQNYU/OrHx93yNDLJMf4SylcLUQAiLxNU97jEoQXA4DVaXZQr5DNwvWrGA9cVjhm38E1mTbryhcQduy+j9+JMLMvcNxFYbRUmIaposu2bY+3c1iVMa4zPBKPAchWlUAm8Lys1r2HwhFCiK1j8YB1rbcPvGS1CppSaT7kj3iel83KTH9X6PLDg58JFVBvJlMag1vy95lSanbWAqzUlQ/YxnfxwwQWFs6ZulVA/hfglJAZGLa6+h4p2PU61xAEV9Nkb+F2NPr7JI/wEpmwi1QB40RFON/Zlhln20flDeGi4jvWRhR2JCtw3T5CogKDLKkPEBQeyqRLgpkrPokSqJbkrIE4b46XUOqtKoPzNECzZ5F+haefn9LxKNKRCQ1OZGzkrU6LhCcz8eDOs5EuX8TZG4iz7nxJaJNg=
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
script:
- node ./internals/scripts/generate-templates-for-linting
- npm test -- --maxWorkers=4
- npm run build
notifications:
  email:
    on_failure: change
after_success: npm run coveralls
cache:
  directories:
  - node_modules
